### ISSUE TITLE
Bootstrap console error.  minor thing

### ISSUE THREAD

**Issue by RudyFiero** [wombat2611/ESP8266NR_PWM_WiFiManager_EEPRO_reset_WiFiManager_Bootstrap#1]
Bootstrap was throwing console errors complaining about no jquery. I reversed the order of the loading to jquery first and then Bootstrap and that got rid of the error. 

`  webpage +="<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js\"></script>\n";
  webpage +="<script src=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js\" integrity=\"sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa\" crossorigin=\"anonymous\"></script>\n";
  `

I like how you did this. I may make use of it at some point.

**Comment by NoamRiter** [comment]
Thank's, I have change the order.
